### ISSUE TITLE
not updated anymore?

### ISSUE THREAD

**Issue by ward0** [linuxserver/docker-home-assistant-armhf#2]
Hello,

This repository is not updated anymore?

**Comment by homerr** [comment]
It looks like this started a couple of years ago in the community, but never got completed/maintained thereafter.

I'll look at this with the team, and if we're all onboard with it I will lead re-releasing it onto all archs.

**Comment by ward0** [comment]
@homerr  I thank you in avance 👍

**Comment by CHBMB** [comment]
[The Readme clearly states it's not been released](https://github.com/linuxserver/docker-home-assistant-armhf#this-is-a-container-in-active-development-by-the-linuxserverio-team-and-is-not-recommended-for-use-by-the-general-public)
